// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbAxeB9PYRv2_uYbWM2MEIEd-ZB89F4Y4',
    appId: '1:1071701599652:web:83de47f4710ec7403ecd31',
    messagingSenderId: '1071701599652',
    projectId: 'financas-f36c6',
    authDomain: 'financas-f36c6.firebaseapp.com',
    storageBucket: 'financas-f36c6.firebasestorage.app',
    measurementId: 'G-GD4NDBG3JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCISSe3iBHmCNCkXB8MOoNZOsQ4b1vg21I',
    appId: '1:1071701599652:android:bf4112e331b50b383ecd31',
    messagingSenderId: '1071701599652',
    projectId: 'financas-f36c6',
    storageBucket: 'financas-f36c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_HMpkwGRJu2sBEdMhFqLPVz0SshKp3H4',
    appId: '1:1071701599652:ios:926995943061c6933ecd31',
    messagingSenderId: '1071701599652',
    projectId: 'financas-f36c6',
    storageBucket: 'financas-f36c6.firebasestorage.app',
    iosBundleId: 'com.example.financas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_HMpkwGRJu2sBEdMhFqLPVz0SshKp3H4',
    appId: '1:1071701599652:ios:926995943061c6933ecd31',
    messagingSenderId: '1071701599652',
    projectId: 'financas-f36c6',
    storageBucket: 'financas-f36c6.firebasestorage.app',
    iosBundleId: 'com.example.financas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbAxeB9PYRv2_uYbWM2MEIEd-ZB89F4Y4',
    appId: '1:1071701599652:web:1849935f4bff07863ecd31',
    messagingSenderId: '1071701599652',
    projectId: 'financas-f36c6',
    authDomain: 'financas-f36c6.firebaseapp.com',
    storageBucket: 'financas-f36c6.firebasestorage.app',
    measurementId: 'G-GT8RTDJJ4M',
  );
}
